<a href="https://colab.research.google.com/github/rajavetha87/Data-Analytics-Using-Python--project-2/blob/main/Copy_of_Day_3%264_internship.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
  num=int(input("Enter Number:"))
  print(num)
except:
  print("Invalid Input")

Enter Number:abc
Invalid Input


In [ ]:
import numpy as np
marks=np.array([90,85,78,92])
print(marks)

[90 85 78 92]


In [ ]:
import numpy as np
students=np.array([
    [90,85],
    [78,92],
    [88,95]
])
print(students)

[[90 85]
 [78 92]
 [88 95]]


In [ ]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
marks=np.array([70,80,90,60])
average=np.mean(marks)
print(average)

75.0


In [ ]:
import numpy as np
salary=np.array([10000,20000,30000,40000,50000])
med=np.median(salary)
print(med)

30000.0
